### PR TITLE
AX-4551: Incomplete List of Disallowed Inputs in @babel/traverse

### PR DESCRIPTION
**Pull request by audiocipher**
This PR is to resolve the critical snyk vulnerability `@babel/traverse Incomplete List of Disallowed Inputs`. 

This vulnerability was introduced through `ember-auto-import@2.2.4, ember-cli-babel@7.26.6` and resolved by upgrading to `@babel/traverse@7.23.2`.

*Note: upgrading to `@babel/traverse@7.23.2` caused errors due to an incompatibility between ember-auto-import and webpack, so an additional change was made to resolve this in ember-cli-build.js.

### CODE REVIEW

**Comment by ross-tew-expel** [comment]
@audiocipher - looking good from a first pass! One thing that comes to mind:
- I'm not sure, but we may need a major release bump for the upgrade of Node 12->16
- See @nabeelz7's comment here on the last PR: https://github.com/expel-io/ember-ajax-fetch/pull/55#issuecomment-1719699724

**Comment by nabeelz7** [comment]
> *Note: upgrading to @babel/traverse@7.23.2 caused errors due to an incompatibility between ember-auto-import and webpack, so an additional change was made to resolve this in ember-cli-build.js.

Unfortunately due to rebuilding `yarn.lock` its hard to tell how many changes are being made here. Was upgrading to node 16 required because of `@babel/traverse@7.23.2`. What version of this package is currently there (to see if it was because of a major bump of this package) -- too lazy to checking myself.

**Comment by audiocipher** [comment]
> > *Note: upgrading to @babel/traverse@7.23.2 caused errors due to an incompatibility between ember-auto-import and webpack, so an additional change was made to resolve this in ember-cli-build.js.
> 
> Unfortunately due to rebuilding `yarn.lock` its hard to tell how many changes are being made here. Was upgrading to node 16 required because of `@babel/traverse@7.23.2`. What version of this package is currently there (to see if it was because of a major bump of this package) -- too lazy to check myself.

@nabeelz7 @ross-tew-expel 
Upgrading to node 16 was required in order to fix the error `webpack returned errors to ember-auto-import` after bumping the direct dependency `ember-cli-babel@7.23.0` to `ember-cli-babel@7.23.2`.

In my latest commit I tried only bumping the transitive dependency `@babel/traverse@7.15.4` to `@babel/traverse@7.23.2`, but I got the same webpack error described above.

**Review by ross-tew-expel — APPROVED** [review]
👍 Thanks for the additional research, AJ - sounds like this is the best path forward

**Pull request merged**
